application:
  name: API-INTRODUCE-V2
  channel: SYSTEM
  organization: NEO JSC
  version: 1.0
  company: NEO JSC
  team: SMSC Team
  author: ManhND
  create-date: 01/01/2024
server:
  port: 8080
  tomcat:
    max-threads: 1000
    accept-count: 2000
    max-connections: 1000
    min-spare-threads: 10
    connection-timeout:
      seconds: 120000
logging:
  #  config: config/log4j2.xml
  file:
    name: logs/web_introdule.log
  level.web: DEBUG
  job:
    sql-insert: insert into log_api(account,channel,msisdn,method,client_ip,req,response,status,msg,trand_id,time_upd,time_ms,api_node) values (?,?,?,?,?,?,?,?,?,?,to_date(?,'yyyy/mm/dd hh24:mi:ss'),?,?)
    batch-size: 5000
    max-retry: 3
    path:
      time-read: 10000
      file-pattern: work-log-inbound*.log
      wait: logs/work/wait
      retry: logs/work/retry
      failed: logs/work/failed
app:
  module:
    ip-db: localhost
    ip-db-log: localhost
spring:
  devtools:
    restart:
      enabled: true
  task:
    scheduling:
      pool:
        size: 10
  main:
    banner-mode: console
  datasource:
    jdbc-url: jdbc:mysql://${app.module.ip-db}:3306/admin?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    minimum-idle: 1
    maximum-pool-size: 10
    auto-commit: true
    connection-timeout: 600000
    idle-timeout: 600000
    max-lifetime: 1800000
    validation-timeout: 600000
    leak-detection-threshold: 100000
    pool-name: ${application.name}
    data-source-properties: v$session.program=${application.name}
  datasource-log:
    jdbc-url: jdbc:mysql://${app.module.ip-db-log}:3306/admin?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    minimum-idle: 1
    maximum-pool-size: 10
    auto-commit: false
    connection-timeout: 600000
    idle-timeout: 600000
    max-lifetime: 1800000
    validation-timeout: 600000
    leak-detection-threshold: 100000
    pool-name: ${application.name}-Log
    data-source-properties: v$session.program=${application.name}-Log
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true