application:
  name: API-BACKEND
  channel: SYSTEM
  organization: NEO JSC
  version: 1.0
  company: NEO JSC
  team: One Team
  author: ManhND
  create-date: 01/01/2024
  des: "API Backend tiếp nhận và xử lý thao tác người dùng"
server:
  port: 3000
  tomcat:
    max-threads: 1000
    accept-count: 2000
    max-connections: 1000
    min-spare-threads: 10
    connection-timeout:
      seconds: 120000
logging:
  #  config: config/log4j2.xml
  file:
    name: logs/web_introdule.log
  level.web: DEBUG
  job:
    sql-insert: insert into log_api(account,channel,msisdn,method,client_ip,req,response,status,msg,trand_id,time_upd,time_ms,api_node) values (?,?,?,?,?,?,?,?,?,?,to_date(?,'yyyy/mm/dd hh24:mi:ss'),?,?)
    batch-size: 5000
    max-retry: 3
    path:
      time-read: 10000
      file-pattern: work-log-inbound*.log
      wait: logs/work/wait
      retry: logs/work/retry
      failed: logs/work/failed
app:
  module:
    ip-db: localhost
    ip-db-log: localhost
spring:
  devtools:
    restart:
      enabled: true
  task:
    scheduling:
      pool:
        size: 10
  main:
    banner-mode: console
  datasource:
    jdbc-url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.ztfewtamedkgmpdhruyt&password=123456a@
    username: postgres.ztfewtamedkgmpdhruyt
    password: 123456a@
    driver-class-name: org.postgresql.Driver
    minimum-idle: 1
    maximum-pool-size: 10
    auto-commit: true
    connection-timeout: 600000
    idle-timeout: 600000
    max-lifetime: 1800000
    validation-timeout: 600000
    leak-detection-threshold: 100000
    pool-name: ${application.name}
    data-source-properties: v$session.program=${application.name}
  datasource-log:
    jdbc-url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.ztfewtamedkgmpdhruyt&password=123456a@
    username: postgres.ztfewtamedkgmpdhruyt
    password: 123456a@
    driver-class-name: org.postgresql.Driver
    minimum-idle: 1
    maximum-pool-size: 10
    auto-commit: false
    connection-timeout: 600000
    idle-timeout: 600000
    max-lifetime: 1800000
    validation-timeout: 600000
    leak-detection-threshold: 100000
    pool-name: ${application.name}-Log
    data-source-properties: v$session.program=${application.name}-Log
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
